# Generated by Django 2.1.8 on 2019-07-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
