# Generated by Django 2.1.8 on 2019-07-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0002_upload_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingduty',
            name='prev_grading_duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventmanager.GradingDuty'),
        ),
        migrations.AddField(
            model_name='gradingduty',
            name='request_subevent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_subevent', to='eventmanager.Subevent'),
        ),
        migrations.AlterField(
            model_name='gradingduty',
            name='subevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevent', to='eventmanager.Subevent'),
        ),
        migrations.AlterField(
            model_name='submissiongroup',
            name='access_code_submitted',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
