# Generated by Django 2.1.8 on 2019-06-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignmentmanager', '0001_initial'),
        ('coursemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhastopics',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanager.Topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_requests_created', to='assignmentmanager.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignmentmanager.QuestionSet'),
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(through='assignmentmanager.QuestionHasTopics', to='coursemanager.Topic'),
        ),
    ]
