# Generated by Django 2.1.8 on 2019-06-19 07:11

from django.db import migrations, models
import django.db.models.deletion
import helper.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('eventmanager', '0001_initial'),
        ('coursemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='subevents',
            field=models.ManyToManyField(through='eventmanager.UserHasSubevents', to='eventmanager.Subevent'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=helper.related.SpanningForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.User', verbose_name='User'),
        ),
    ]
