version: "3"
services:
  app:
    restart: always
    build: .
    #python3 manage.py migrate &&
    command: bash -c "python3 manage.py collectstatic --no-input &&  gunicorn --timeout=120 --workers=2 --bind :8000 SmartGrader.wsgi:application"
    volumes:
      - .:/code
      - static-volume:/code/static
    expose:
      - "8000"
    ports:
      - "0.0.0.0:3000:8000"
    depends_on:
      - db
      - memcached
    networks:
      - web_network
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./sqlscripts:/sqlscripts"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=django_app
      - MYSQL_USER=django_app
      - MYSQL_PASSWORD=django_app123
    networks:
      - web_network
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "3000:8000"
  #   volumes:
  #     - static-volume:/code/static
  #     - ./config/nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - app
  #   networks:
  #     - web_network

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  # db_network:
  #   driver: bridge

volumes:
  static-volume: